
--

CREATE TABLE IF NOT EXISTS `thematic_hirlev` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `hirlev_id` int(11) NOT NULL,
  `sendingdate` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `folder` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `analytics_source` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `analytics_medium` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `menu1` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `menu1_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `menu1_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `menu2` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `menu2_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `menu2_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `menu3` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `menu3_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `menu3_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `menu4` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `menu4_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `menu4_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `menu5` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `menu5_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `menu5_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp_pic` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp_title` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp_text` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp_price` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp_orig_price` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `bp_discount` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `bp2_ok` tinytext,
  `bp2_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp2_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp2_pic` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp2_title` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp2_text` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp2_price` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp2_orig_price` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `bp2_discount` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `bp3_ok` tinytext,
  `bp3_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp3_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp3_pic` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp3_title` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp3_text` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp3_price` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `bp3_orig_price` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `bp3_discount` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `article_ok` tinytext,
  `harticle_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `harticle_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `harticle_title` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `harticle_date` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `harticle_text` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `article_1_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `article_1_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `article_1_title` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `article_1_date` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `article_2_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `article_2_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `article_2_title` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `article_2_date` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `article_3_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `article_3_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `article_3_title` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `article_3_date` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `article_4_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `article_4_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `article_4_title` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `article_4_date` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `ad_ok` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `banner_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `banner_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `banner_pic` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `textad_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `textad_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `textad_pic` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `textad_title` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `textad_text` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `turpan_1_title` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `turpan_1_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `turpan_2_title` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `turpan_2_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `turpan_3_title` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `turpan_3_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `turpan_4_title` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `turpan_4_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  `ad2_ok` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `banner2_1_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `banner2_1_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `banner2_1_pic` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `banner2_2_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `banner2_2_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `banner2_2_pic` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `textad2_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `textad2_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `textad2_pic` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `textad2_title` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `textad2_text` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `textad2_2_link` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `textad2_2_analytics` tinytext CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `textad2_2_pic` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `textad2_2_title` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  `textad2_2_text` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=100 ;

